services:
    setNewFacture:
      class: AppBundle\Services\GetFacture
      arguments: [@service_container]

    setNewReference:
      class: AppBundle\Services\GetReference
      arguments: [@security.context, @doctrine.orm.entity_manager]

    tva:
      class: AppBundle\Twig\Extension\TvaExtension
      tags:
        - { name: twig.extension }

    montantTva:
      class: AppBundle\Twig\Extension\MontantTvaExtension
      tags:
        - { name: twig.extension }

    redirectionListener:
      class: AppBundle\Listener\RedirectionListener
      arguments: [@service_container,@session]
      tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }